### ISSUE TITLE
Builds on Cygwin are broken after 2ef3254fe1b2f57d4833b2c1ddb100874b41f4a7

### ISSUE THREAD

**Issue by louist103** [weidai11/cryptopp#1109]
After cloning `2ef3254fe1b2f57d4833b2c1ddb100874b41f4a7` the library can not be built on Cygwin, (and likely WSL and other linux like environments)
```
osrng.cpp: In constructor ‘CryptoPP::BlockingRng::BlockingRng()’:
osrng.cpp:256:36: error: ‘O_NOFOLLOW’ was not declared in this scope
  256 |         const int flags = O_RDONLY|O_NOFOLLOW;
      |                                    ^~~~~~~~~~
make: *** [GNUmakefile:1801: osrng.o] Error 1
make: *** Waiting for unfinished jobs....
```
```
$ uname -a
CYGWIN_NT-10.0 DESKTOP-0VCFDU8 3.3.4(0.341/5/3) 2022-01-31 19:35 x86_64 Cygwin
```

**Comment by noloader** [comment]
Sorry about that @louist103,

It should be fixed with [Commit 458a69fdbca9](https://github.com/weidai11/cryptopp/commit/458a69fdbca9).
