### ISSUE TITLE
Commit ccd59710 broke Keccak

### ISSUE THREAD

**Issue by mouse07410** [weidai11/cryptopp#292]
Current master fails to compile. Keccak got broken by commit ccd59710 (was it tested before merging?):
```
. . . . .
clang++ -maes -mpclmul -mrdrnd -msse2 -mssse3 -msse4.2 -mtune=native -Os -Ofast -std=c++11 -fPIC -march=native -pipe -c keccak.cpp
In file included from keccak.cpp:18:
./keccak.h:81:40: error: constexpr function's return type 'std::string' (aka 'basic_string<char,
      char_traits<char>, allocator<char> >') is not a literal type
        CRYPTOPP_CONSTEXPR static std::string StaticAlgorithmName() { return "Keccak-" + IntToStri...
                                              ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string:4271:48: note: 
      'basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >' is not literal because
      it is not an aggregate and has no constexpr constructors other than copy or move constructors
_LIBCPP_EXTERN_TEMPLATE(class _LIBCPP_TYPE_VIS basic_string<char>)
                                               ^
In file included from keccak.cpp:18:
./keccak.h:82:34: error: virtual function cannot be constexpr
        CRYPTOPP_CONSTEXPR unsigned int BlockSize() const { return BLOCKSIZE; }
                                        ^
./cryptlib.h:984:23: note: overridden virtual function is here
        virtual unsigned int BlockSize() const {return 0;}
                             ^
2 errors generated.
make: *** [keccak.o] Error 1
```

```
$ git blame keccak.h
. . . . .
cd59710 (DevJPM         2016-09-20 11:27:25 +0200  80)         Keccak_Final() : Keccak(DIGESTSIZE) {}
ccd59710 (DevJPM         2016-09-20 11:27:25 +0200  81)         CRYPTOPP_CONSTEXPR static std::string StaticAlgorithmName() { return "Keccak-" + IntToString(DIGESTSIZE * 8); }
. . . . .
```

Mac OS X 10.11.6, Xcode-8.0.

**Comment by noloader** [comment]
Reverted at [Commit c298dfdbb017076d](http://github.com/weidai11/cryptopp/commit/c298dfdbb017076de1e2f1b6bb8ccd00fe85fb95).

It was not a revert as there were merge errors. I checkout out the proceeding commit, and then made the proceeding one the current one.

My bad. Sorry about that.

**Comment by mouse07410** [comment]
I confirm - everything's smooth again on Mac OS X.
