### ISSUE TITLE
Linker error under vcpkg

### ISSUE THREAD

**Issue by steronydh** [weidai11/cryptopp#606]
Windows 10 Pro 64-bit; vcpkg; version 5.6.5-1; VS2015

I've just updated my vcpkg libraries and when I link to Cryptopp I'm getting this linker error:

```
2>cryptopp-static.lib(integer.obj) : error LNK2019: unresolved external symbol ___std_reverse_trivially_swappable_1 referenced in function
"public: __thiscall CryptoPP::Integer::Integer(class CryptoPP::BufferedTransformation &,unsigned int,
enum CryptoPP::Integer::Signedness,enum CryptoPP::ByteOrder)" (??0Integer@CryptoPP@@QAE@AAVBufferedTransformation@1@IW4Signedness@01@
W4ByteOrder@1@@Z) in module cryptopp-static.lib(integer.obj)
```

I think it's probably a setting somewhere but I can't see anything obvious so any suggestions would be welcome.

**Comment by steronydh** [comment]
@noloader Thanks for the feedback. I don't have any problems with 5.6.4 so I think I will stick with that until Vcpkg supports Crypto++ 6.1 (although it appears that [Crypto++ is dropping support for CMake](https://github.com/Microsoft/vcpkg/issues/3039) which may be a problem there).

**Comment by noloader** [comment]
> although it appears that Crypto++ is dropping support for CMake which may be a problem there

It is not as bad as it sounds. CMake never got stable so we moved it into my GitHub. It is available at [Noloader | CMake](https://github.com/noloader/cryptopp-cmake). If CMake ever gets stable then we can move it back to the library proper.

CMake has a couple of contributors so it might slowly get stable over time. If you want to contribute then I can make you a collaborator at [Noloader | CMake](https://github.com/noloader/cryptopp-cmake).

I also tweak the CMake files on occasion when the Makefile needs a tweak. I just don't have the time to spend on the CMake problems.

**Comment by noloader** [comment]
@steronydh,

Is it OK to close this report, or do we need to keep it open?

**Comment by steronydh** [comment]
Yes, please close it.

**Comment by firexx** [comment]
I have the link error in 7.0 like similar as above 
`1>integer.obj : error LNK2019: unresolved external symbol ___std_reverse_trivially_swappable_1 referenced in function "void __cdecl std::_Reverse_unchecked1<unsigned char *>(unsigned char * const,unsigned char * const,struct std::integral_constant<unsigned int,1>)" (??$_Reverse_unchecked1@PAE@std@@YAXQAE0U?$integral_constant@I$00@0@@Z)`
and some additional one:
`1>winpipes.obj : error LNK2019: unresolved external symbol __imp__GetOverlappedResultEx@20 referenced in function __catch$??1WindowsHandle@CryptoPP@@UAE@XZ$0`

**Comment by noloader** [comment]
@firexx,

I don't have any ideas for your first issue. The missing symbols from `integer.o` coe from the C++ libraries, not Crypto++.

I also don't have any ideas for your second issue. We recently removed the Sockets and Pipes gear because it was causing problems. Also see [Issue 208, Investigate moving OS specific Socket and Thread to the Patch Page](https://github.com/weidai11/cryptopp/issues/208) and [ThreadLocalStorage](https://www.cryptopp.com/wiki/ThreadLocalStorage) on the wiki.

**Comment by firexx** [comment]
i going back to 5.6.1 and it works again. don't no why 7.0.0 have a problems...

**Comment by tungsten106** [comment]
Windows 11 Arm64EC; vcpkg; version 8.9.0; VS2022

I have also met a similar linker error after linking my cryptest solution to the cryptopp.lib build from vcpkg:

```
unresolved external symbol "void __cdecl CryptoPP::DetectX86Features(void)" (?DetectX86Features@CryptoPP@@YAXXZ) referenced in function "void __cdecl CryptoPP::DetectX86Features$exit_thunk(void)" (?DetectX86Features$exit_thunk@CryptoPP@@$$hYAXXZ) (EC Symbol)
```
I think there might be some setting I'm missing but I can't find any. Could you give any advices? Anything could help!

**Comment by classix-do** [comment]
This is a bit late to the party, but I encountered a similar linker error when updating cryptopp and wanted to share the solution here.

For me the symbol `__std_reverse_copy_trivially_copyable_1` was unresolved (and also referenced in `integer.obj`).

The solution for me was to ensure that the vc tools versions match between cryptopp and our project (`<VCToolsVersion>` and `<VCToolsRedistVersion>` in .vcxproj or in VS2019: Project Properties -> Advanced -> MSVC Toolset Version).

Cryptlib was build with 14.29.30133 and our program was (for compatibility reasons) built with 14.24.28314.
Looking at the algorithm headers reveals that they significantly changed between these versions and also introduced functions like `__std_reverse_copy_trivially_copyable_1`  (and `___std_reverse_trivially_swappable_1`)

`std::reverse_copy` in 14.24.28314:
```cpp
template <class _BidIt, class _OutIt>
_OutIt reverse_copy(_BidIt _First, _BidIt _Last, _OutIt _Dest) {
    // copy reversing elements in [_First, _Last)
    _Adl_verify_range(_First, _Last);
    const auto _UFirst = _Get_unwrapped(_First);
    auto _ULast        = _Get_unwrapped(_Last);
    auto _UDest        = _Get_unwrapped_n(_Dest, _Idl_distance<_BidIt>(_UFirst, _ULast));
    for (; _UFirst != _ULast; ++_UDest) {
        *_UDest = *--_ULast;
    }

    _Seek_wrapped(_Dest, _UDest);
    return _Dest;
}
```

`std::reverse_copy` in 14.29.30133:
```cpp
template <class _BidIt, class _OutIt>
_CONSTEXPR20 _OutIt reverse_copy(_BidIt _First, _BidIt _Last, _OutIt _Dest) {
    // copy reversing elements in [_First, _Last)
    _Adl_verify_range(_First, _Last);
    const auto _UFirst = _Get_unwrapped(_First);
    auto _ULast        = _Get_unwrapped(_Last);
    auto _UDest        = _Get_unwrapped_n(_Dest, _Idl_distance<_BidIt>(_UFirst, _ULast));

#if _USE_STD_VECTOR_ALGORITHMS
    using _Elem                         = remove_reference_t<_Iter_ref_t<remove_const_t<decltype(_UFirst)>>>;
    using _DestElem                     = remove_reference_t<_Iter_ref_t<decltype(_UDest)>>;
    constexpr bool _Allow_vectorization = conjunction_v<is_same<remove_const_t<_Elem>, _DestElem>,
        bool_constant<_Iterators_are_contiguous<decltype(_UFirst), decltype(_UDest)>>, is_trivially_copyable<_Elem>,
        negation<is_volatile<_Elem>>>;
    constexpr size_t _Nx                = sizeof(_Elem);

#pragma warning(suppress : 6326) // Potential comparison of a constant with another constant
    if constexpr (_Allow_vectorization && _Nx <= 8 && (_Nx & (_Nx - 1)) == 0) {
#ifdef __cpp_lib_is_constant_evaluated
        if (!_STD is_constant_evaluated())
#endif // __cpp_lib_is_constant_evaluated
        {
            if constexpr (_Nx == 1) {
                __std_reverse_copy_trivially_copyable_1(_To_address(_UFirst), _To_address(_ULast), _To_address(_UDest));
            } else if constexpr (_Nx == 2) {
                __std_reverse_copy_trivially_copyable_2(_To_address(_UFirst), _To_address(_ULast), _To_address(_UDest));
            } else if constexpr (_Nx == 4) {
                __std_reverse_copy_trivially_copyable_4(_To_address(_UFirst), _To_address(_ULast), _To_address(_UDest));
            } else {
                __std_reverse_copy_trivially_copyable_8(_To_address(_UFirst), _To_address(_ULast), _To_address(_UDest));
            }

            _UDest += _ULast - _UFirst;
            _Seek_wrapped(_Dest, _UDest);
            return _Dest;
        }
    }
#endif // _USE_STD_VECTOR_ALGORITHMS

    for (; _UFirst != _ULast; ++_UDest) {
        *_UDest = *--_ULast;
    }

    _Seek_wrapped(_Dest, _UDest);
    return _Dest;
}
```

> I have the link error in 7.0 like similar as above `1>integer.obj : error LNK2019: unresolved external symbol ___std_reverse_trivially_swappable_1 referenced in function "void __cdecl std::_Reverse_unchecked1<unsigned char *>(unsigned char * const,unsigned char * const,struct std::integral_constant<unsigned int,1>)" (??$_Reverse_unchecked1@PAE@std@@YAXQAE0U?$integral_constant@I$00@0@@Z)` and some additional one: `1>winpipes.obj : error LNK2019: unresolved external symbol __imp__GetOverlappedResultEx@20 referenced in function __catch$??1WindowsHandle@CryptoPP@@UAE@XZ$0`

The first issue could very likely be caused by the same problem of mismatched vc runtime versions between cryptopp and your project linking to it.
